### ISSUE TITLE
I am getting your emails (probably)

### ISSUE THREAD

**Issue by teverding** [taylor1791/glider#82]
Hi!

My name is Thomas Everding. I am sorry to contact you in such a strange way...

I am continously getting job proposals to my mail address [REDACTED] as a software engineer directed to a 'Taylor Everding'.
This might be for you.

I answered some ('Sorry, I am not Taylor...') but I guess you might be interested in those mails.

Yesterday, I got a mail from Susan Hoffman <Susan.Hoffman@mdc.mo.gov> on 'Saturday's Spring Waterway Clean-up Info'.

If these mails are not for you (but another Taylor Everding) just delete this issue. SORRY

Otherwise you might want to change the mail address at job-proposal-something-page and on Susan's list.
I can forward Susan's mail to you, just send me a mail (see above).

Best,
Thomas

**Comment by taylor1791** [comment]
Hey Thomas!

I sent you an email. It should contain everything you need. Finally, I edited your comment to avoid spammers from discovering it.
